### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by saunders241** [hook/champions#140]
Has the project been abandoned?  No update on Mephisto or anything else, and looks like last update was August.

**Comment by Marzipan87** [comment]
seems to be...
very sad

**Comment by BillyNate** [comment]
I've created a pull request (#141) containing the champions of September and October.
Unfortunately I couldn't add the November champions because the game now handles its files differently and I don't know how to get to the images of Hela and Thor Ragnarok.
Also I couldn't add the synergies, because they're mostly new ones, and are very specific 😣 
So, we'll now have to wait a bit for the PR to be accepted.
If any of you happen to have the images of the new champions (or knows how to get them), feel free to let me know so we can add these.
And remember this is open source, so if this project is abandoned you van fork it and start adding the new/missing data yourself 😉

**Comment by ioshta** [comment]
@BillyNate I will happily do so if you can teach me or direct me on how to learn it. Cause I love this tool and would hate to see it die.

**Comment by KuruptdOne** [comment]
How do we add or change stuff? I would like to help keep this going.

**Comment by hook** [comment]
I'll review and merge PRs, I've just been out of commission for a while. I'll do some more work in the future when i get inspired!

**Comment by hook** [comment]
I would say it's more on sabbatical than abandoned.

**Comment by KuruptdOne** [comment]
That's great to hear! I love the usefulness of all this. If it had a mastery build too. So I could look at My current setup and or see how my champ were impacted by changes to my setup....be perfect. Probably too perfect. Lol

**Comment by ioshta** [comment]
We are glad you are alright, If there is anything we can do to assist you let us know. Thank you for all you do.

**Comment by KuruptdOne** [comment]
Awesome to see you at work again. Saw a typo. Medusa is a skill champ. But she's actually Cosmic

**Comment by user23498723452** [comment]
@saunders241 please clsoe this out
