### ISSUE TITLE
Optional Defense/Attack tracking

### ISSUE THREAD

**Issue by JasonJW** [hook/champions#8]
Thanks to your roster manager, and my exported file - I noticed that the PI of 3S Ultron increased 11.0705596% after duping.  Masteries are the same, so that bump is from the duplication.  Unfortunately, I did not track or take not of Defense or Attack.

In the same way that the user can optionally track PI, **can you add fields to track Health and Attack?**  **And also export those values to the CSV record?**

**Comment by hook** [comment]
I'd actually rather stay away from specific stats since those seem to change the most, and the majority of them (champion specific crit rates/armor/etc.) aren't known.

Is there a specific use case for attack/defense ratings, or just something nice to have? I'm also pretty sure attack/defense does not change with duplication, just the PI (depending on masteries as well).

**Comment by hook** [comment]
Gonna close this for now. Full stats would be nice, but until they release more details I'd rather stick to PI only. We can reference spreadsheets for this data (especially since it's heavily mastery dependent).
